module.exports.cocofarsi = (objname) => {
  const cocofarsilist = {
    person: "شخص",
    bicycle: "دوچرخه",
    car: "خودرو",
    motorcycle: "موتور",
    airplane: "هواپیما",
    bus: "اتوبوس",
    train: "قطار",
    truck: "کامیون",
    boat: "قایق",
    "traffic light": "چراغ راهنمایی",
    "fire hydrant": "شیر آتشنشانی",
    "stop sign": "علامت توقف",
    "parking meter": "پارکینگ متر",
    bench: "نیمکت",
    bird: "پرنده",
    cat: "گربه",
    dog: "سگ",
    horse: "اسب",
    sheep: "گوسفند",
    cow: "گاو",
    elephant: "فیل",
    bear: "خرس",
    zebra: "گورخر",
    giraffe: "زرافه",
    backpack: "کول پشتی",
    umbrella: "چتر",
    handbag: "کیف دستی",
    tire: "چرخ",
    suitcase: "کیف",
    frisbee: "فریزبی",
    skis: "اسکی",
    snowboard: "اسنوبرد",
    "sports ball": "توپ ورزشی",
    kite: "کایت",
    "baseball bat": "چوب بیسبال",
    "baseball glove": "دستکش بیسبال",
    skateboard: "اسکیت برد",
    surfboard: "تخته موج سواری",
    "tennis racket": "راکت تنیس",
    bottle: "بطری",
    "wine glass": "گیلاس شراب",
    cup: "فنجان",
    fork: "چنگال",
    knife: "چاقو",
    spoon: "قاشق",
    bowl: "کاسه",
    banana: "موز",
    apple: "سیب",
    sandwich: "ساندویچ",
    orange: "پرتقال",
    broccoli: "بروکلی",
    carrot: "هویج",
    "hot fog": "هات داگ",
    pizza: "پیتزا",
    donut: "دونات",
    cake: "کیک",
    chair: "صندلی",
    couch: "مبل",
    "potted plant": "گلدان",
    bed: "تخت خواب",
    "dining table": "میز ناهارخوری",
    toilet: "دستشویی",
    tv: "تلویزیون",
    laptop: "لپ تاپ",
    mouse: "موس",
    remote: "ریموت کنرتل",
    keyboard: "کیبورد",
    "cell phone": "موبایل",
    microwave: "ماکروفر",
    oven: "فر",
    toaster: "توستر",
    sink: "سینک",
    refrigerator: "یخچال",
    book: "کتاب",
    clock: "ساعت",
    vase: "گلدان",
    scissors: "قیچی",
    "teddy bear": "خرسی",
    "hair drier": "سشوار",
    toothbrush: "مسواک",
  };

  return cocofarsilist[objname];
}

